### ISSUE TITLE
Add restart logic

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/Bubble-Poke#10]
After getting three misses, the game should get redirected to a "You lost, Your score {score}" page which then sends the user to Menu. #9

**Comment by 0x48piraj** [comment]
Pinging the contributors @AmrAbdelhameed @ItzzRitik

**Comment by FedeX15** [comment]
Can you add a part in the javascript where you check whenever the "escaped" var reaches 3?

**Comment by FedeX15** [comment]
> Can you add a part in the javascript where you check whenever the "escaped" var reaches 3?

Tried myself, working on it and submitting a pull request in a few minutes

**Comment by FedeX15** [comment]
I suggest to close this issue
