### ISSUE TITLE
Port to Android [WPA]

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/Bubble-Poke#2]
Help in porting this web based game to Android. Free to use frameworks if needed.

**Comment by buddakushpr0** [comment]
[c_camerat.txt](https://github.com/0x48piraj/Bubble-Poke/files/2452818/c_camerat.txt)

**Comment by ItzzRitik** [comment]
Resolved right?

**Comment by 0x48piraj** [comment]
Indeed.
