### ISSUE TITLE
Add a start menu

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/Bubble-Poke#9]
- Start Game, Quit
- Using Back Button, Menu should activate

**Comment by 0x48piraj** [comment]
After Splash Screen, Menu should open, as directly getting into the game is little abrupt.

**Comment by 0x48piraj** [comment]
Pinging the contributors @AmrAbdelhameed @ItzzRitik

**Comment by FedeX15** [comment]
Working on it

**Comment by FedeX15** [comment]
Pull request submitted
